/*
 * Sample API
 *
 * A sample API that uses a sample-site as an example to demonstrate features in the OpenAPI 3.0 specification
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
)

func main() {
	log.Printf("started server on 0.0.0.0:8080, url: http://localhost:8080")

	// TODO: DefaultApiServiceを実装する
	// DefaultApiService := openapi.NewDefaultApiService()
	// DefaultApiController := openapi.NewDefaultApiController(DefaultApiService)

	// router := openapi.NewRouter(DefaultApiController)

	// log.Fatal(http.ListenAndServe(":8080", router))
}
